# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f823d225029390b5794cf3c4d30952a4a60f23368e264e6b15601f2e70d0c29b2b2ac37cb7123c7626237e444e62db69a1d1f8c33983ab83efd53fadf42fa24

test:
  secret_key_base: 0d9641adeb0fffcf1caca7a24fedfa19443f27931314c4c030732be61097e4b07e806c5db6feb380114fde550d64e03dcfd8651e938bb295ad2b89ea227660c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
